import Vue from "vue";
import '@mdi/font/css/materialdesignicons.css';
import 'vuetify/dist/vuetify.min.css';

import Vuetify, {
    VNavigationDrawer,
    VBottomSheet,
    VApp,
    VDialogBottomTransition,
    VBtn,
    VCol,
    VRow,
    VSpacer,
    VDivider,
    VContainer,
    VTextField,
    VList,
    VListItemGroup,
    VListItem,
    VListItemTitle,
    VListItemSubtitle,
    VListItemContent,
    VListItemAction,
    VMain,
    VFooter,
    VOverlay,
    VIcon,
    VSheet,
    VProgressCircular,
    VTooltip,
    VCheckbox,
    VSubheader,
    VListGroup,
    VBadge,
    VDialog,
    VVirtualScroll,
    VCard,
    VCardText,
    VCardTitle,
    VCardActions,
    VDataTable,
    VTabs,
    VTabsItems,
    VTab,
    VTabItem,
    VToolbar,
    VToolbarTitle,
    VToolbarItems,
} from "vuetify/lib";

import { Ripple } from "vuetify/lib/directives";

Vue.use(Vuetify, {
    components: {
        VTooltip,
        VNavigationDrawer,
        VBottomSheet,
        VApp,
        VDialogBottomTransition,
        VBtn,
        VCol,
        VRow,
        VSpacer,
        VDivider,
        VContainer,
        VTextField,
        VList,
        VListItemGroup,
        VListItem,
        VListItemTitle,
        VListItemSubtitle,
        VListItemAction,
        VListItemContent,
        VMain,
        VFooter,
        VOverlay,
        VIcon,
        VSheet,
        VProgressCircular,
        VCheckbox,
        VSubheader,
        VListGroup,
        VBadge,
        VDialog,
        VCard,
        VCardText,
        VCardTitle,
        VCardActions,
        VVirtualScroll,
        VDataTable,
        VTabs,
        VTab,
        VTabsItems,
        VTabItem,
        VToolbar,
        VToolbarTitle,
        VToolbarItems,
    },
    directives: {
        Ripple
    }
});

export default new Vuetify();

